// TLS-terminated uWebSockets.js back-end (SSLApp) for the request-smuggling PoC.
//
// Same catch-all reporting handler as backend_uwsjs.js, but uWS terminates TLS
// itself (uWS::SSLApp) — so the HTTPS request is parsed by the SAME upstream
// uWebSockets C++ HttpParser, over a TLS connection. Use this to confirm the
// A/B/C deviations are reachable over HTTPS with smuggle_probe_tls.go.
//
// Cert/key: self-signed, generated by the caller (see run_tls.sh). Paths come
// from env TLS_KEY / TLS_CERT (defaults below); port from env PORT (default 9443).

const uWS = require('uWebSockets.js');
const fs = require('fs');
const path = require('path');

let VERSION = 'unknown', COMMIT = 'unknown';
try {
  const base = path.dirname(require.resolve('uWebSockets.js'));
  VERSION = JSON.parse(fs.readFileSync(path.join(base, 'package.json'), 'utf8')).version;
  COMMIT = fs.readFileSync(path.join(base, 'source_commit'), 'utf8').trim();
} catch (_) {}

const KEY = process.env.TLS_KEY || path.join(__dirname, 'tls', 'key.pem');
const CERT = process.env.TLS_CERT || path.join(__dirname, 'tls', 'cert.pem');
const PORT = parseInt(process.env.PORT || '9443', 10);

uWS.SSLApp({ key_file_name: KEY, cert_file_name: CERT })
  .any('/*', (res, req) => {
    const method = req.getMethod();
    const url = req.getUrl();
    const cookie = req.getHeader('cookie');
    const smuggled = req.getHeader('x-smuggled');
    process.stderr.write(
      `[BACKEND-TLS] PARSED  method=${method} url=${url} cookie="${cookie}" x-smuggled="${smuggled}"\n`
    );
    res.onAborted(() => {});
    res.end(`BACKEND-SAW method=${method} url=${url} cookie=${cookie} x-smuggled=${smuggled}\n`);
  })
  .listen('127.0.0.1', PORT, (token) => {
    if (token) {
      process.stderr.write(
        `[BACKEND-TLS] uWebSockets.js v${VERSION} (upstream commit ${COMMIT}) SSLApp listening on 127.0.0.1:${PORT} (https)\n`
      );
    } else {
      process.stderr.write(`[BACKEND-TLS] FAILED to listen on ${PORT} (bad cert/key? see TLS_KEY/TLS_CERT)\n`);
      process.exit(1);
    }
  });
